### ISSUE TITLE
Analyse button gives internal server error

### ISSUE THREAD

**Issue by zak-ahmed** [carlwilson/fmt-sniff#29]
From the home page - select either Test bucket or local folder
Select a folder and click on Analyse button
Result: Gives internal server error page

Logs :
host;x-amz-content-sha256;x-amz-date
e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
[auth.py        :350  ] StringToSign:
AWS4-HMAC-SHA256
20171102T061539Z
20171102/eu-west-2/s3/aws4_request
35358d55348dd71b67db0a96c83e7ba5c9f10958c4229faada51ddc84741560c
[auth.py        :352  ] Signature:
dc07b0ed5ca53986723969cc793f23ef02c14a134ab1c50bb03684419e161591
[endpoint.py    :200  ] Sending http request: <PreparedRequest [GET]>
[connectionpool.py:735  ] Starting new HTTPS connection (1): s3.eu-west-2.amazonaws.com
[connectionpool.py:383  ] "GET /testdata.researchdata.alpha.jisc.ac.uk?list-type=2&prefix=unsorted%2F10.1002%2F%2528SICI%25291099-0720%2528199802%252912%3A1%253C35%3A%3AAID-ACP485%253E3.0.CO%3B2-2%2F&delimiter=%2F HTTP/1.1" 200 None
[parsers.py     :204  ] Response headers: {'x-amz-id-2': '5G6cxm49ZGO/UaX16cuGyA6xOwz/N0qKRARUjJL03TfWhBt+Eok+ZLgSGDW1PooR16MFXjfSsW8=', 'x-amz-request-id': '1F25596CB0BF86BA', 'date': 'Thu, 02 Nov 2017 06:15:22 GMT', 'x-amz-bucket-region': 'eu-west-2', 'content-type': 'application/xml', 'transfer-encoding': 'chunked', 'server': 'AmazonS3'}
[parsers.py     :205  ] Response body:
b'<?xml version="1.0" encoding="UTF-8"?>\n<ListBucketResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><Name>testdata.researchdata.alpha.jisc.ac.uk</Name><Prefix>unsorted/10.1002/%28SICI%291099-0720%28199802%2912:1%3C35::AID-ACP485%3E3.0.CO;2-2/</Prefix><KeyCount>1</KeyCount><MaxKeys>1000</MaxKeys><Delimiter>/</Delimiter><IsTruncated>false</IsTruncated><Contents><Key>unsorted/10.1002/%28SICI%291099-0720%28199802%2912:1%3C35::AID-ACP485%3E3.0.CO;2-2/10-1002-%28SICI%291099-0720%28199802%2912:1%3C35::AID-ACP485%3E3-0-CO;2-2.json</Key><LastModified>2017-01-24T16:29:08.000Z</LastModified><ETag>&quot;2a6cd15b9a625c5cbc55e3c3eadbb8d3&quot;</ETag><Size>2206</Size><StorageClass>STANDARD</StorageClass></Contents></ListBucketResult>'
[hooks.py       :209  ] Event needs-retry.s3.ListObjectsV2: calling handler <botocore.retryhandler.RetryHandler object at 0x1074c36a0>
[retryhandler.py:187  ] No retry needed.
[hooks.py       :209  ] Event needs-retry.s3.ListObjectsV2: calling handler <bound method S3RegionRedirector.redirect_from_error of <botocore.utils.S3RegionRedirector object at 0x10a49b4e0>>
[controller.py  :134  ] Shutting down database session with exception.
[_internal.py   :87   ] 127.0.0.1 - - [02/Nov/2017 06:15:39] "POST /reports/ HTTP/1.1" 500 -

**Comment by carlwilson** [comment]
Hi @zak-ahmed I think that this has been fixed by a previous check in. I can now analyse a folder for both S3 bucket and on the local FS. Try the latest integration branch and let me know. I've also documented the way you go about adding folders and buckets through the config file.

I'll keep this open until you can test whether you can reproduce the problem.

**Comment by carlwilson** [comment]
Definitely fixed.
