### ISSUE TITLE
Download button gives server error

### ISSUE THREAD

**Issue by zak-ahmed** [carlwilson/fmt-sniff#31]
Steps: 
1. From home page select test bucket or local folder
2. Select a folder
3. Report will run and display the result
4. Click on Download button 
Result : Gives internal server error page instead of downloading the report

Logs:
[hooks.py       :209  ] Event before-parameter-build.s3.HeadBucket: calling handler <function validate_bucket_name at 0x1071108c8>
[hooks.py       :209  ] Event before-parameter-build.s3.HeadBucket: calling handler <bound method S3RegionRedirector.redirect_from_cache of <botocore.utils.S3RegionRedirector object at 0x107538080>>
[hooks.py       :209  ] Event before-parameter-build.s3.HeadBucket: calling handler <function generate_idempotent_uuid at 0x107110510>
[hooks.py       :209  ] Event before-call.s3.HeadBucket: calling handler <function add_expect_header at 0x107110d90>
[hooks.py       :209  ] Event before-call.s3.HeadBucket: calling handler <bound method S3RegionRedirector.set_request_url of <botocore.utils.S3RegionRedirector object at 0x107538080>>
[endpoint.py    :140  ] Making request for OperationModel(name=HeadBucket) (verify_ssl=True) with params: {'url_path': '/testdata.researchdata.alpha.jisc.ac.uk', 'query_string': {}, 'method': 'HEAD', 'headers': {'User-Agent': 'Boto3/1.4.4 Python/3.6.1 Darwin/16.7.0 Botocore/1.5.95 Resource'}, 'body': b'', 'url': 'https://s3.eu-west-2.amazonaws.com/testdata.researchdata.alpha.jisc.ac.uk', 'context': {'client_region': 'eu-west-2', 'client_config': <botocore.config.Config object at 0x107346588>, 'has_streaming_input': False, 'auth_type': None, 'signing': {'bucket': 'testdata.researchdata.alpha.jisc.ac.uk'}}}
[hooks.py       :209  ] Event request-created.s3.HeadBucket: calling handler <bound method RequestSigner.handler of <botocore.signers.RequestSigner object at 0x107346128>>
[hooks.py       :209  ] Event choose-signer.s3.HeadBucket: calling handler <function set_operation_specific_signer at 0x107110400>
[hooks.py       :209  ] Event before-sign.s3.HeadBucket: calling handler <function fix_s3_host at 0x106fcf488>
[auth.py        :347  ] Calculating signature using v4 auth.
[auth.py        :348  ] CanonicalRequest:
HEAD
/testdata.researchdata.alpha.jisc.ac.uk

host:s3.eu-west-2.amazonaws.com
x-amz-content-sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
x-amz-date:20171102T062147Z

host;x-amz-content-sha256;x-amz-date
e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
[auth.py        :350  ] StringToSign:
AWS4-HMAC-SHA256
20171102T062147Z
20171102/eu-west-2/s3/aws4_request
49f3ab898ef061294e0852b6ac0e3fd643d60ebf51032c25c114c1f10bfb7ac3
[auth.py        :352  ] Signature:
77cf41efdcb20de0200a6ba34877bf3585f52f4fd6286482b32e7628c374db43
[endpoint.py    :200  ] Sending http request: <PreparedRequest [HEAD]>
[connectionpool.py:735  ] Starting new HTTPS connection (106): s3.eu-west-2.amazonaws.com
[connectionpool.py:383  ] "HEAD /testdata.researchdata.alpha.jisc.ac.uk HTTP/1.1" 200 0
[parsers.py     :204  ] Response headers: {'x-amz-id-2': 'r6AZxyJv5CfWWej76c1sODQDX94CbD/GtTo813jlyenUf6cTD7LQe9QSM19lA0L9Y3irxFg9LAs=', 'x-amz-request-id': 'AAFD7035B8F2B6A5', 'date': 'Thu, 02 Nov 2017 06:21:31 GMT', 'x-amz-bucket-region': 'eu-west-2', 'content-type': 'application/xml', 'transfer-encoding': 'chunked', 'server': 'AmazonS3'}
[parsers.py     :205  ] Response body:
b''
[hooks.py       :209  ] Event needs-retry.s3.HeadBucket: calling handler <botocore.retryhandler.RetryHandler object at 0x1074c36a0>
[retryhandler.py:187  ] No retry needed.
[hooks.py       :209  ] Event needs-retry.s3.HeadBucket: calling handler <bound method S3RegionRedirector.redirect_from_error of <botocore.utils.S3RegionRedirector object at 0x107538080>>
[client.py      :115  ] Registering retry handlers for service: s3
[hooks.py       :209  ] Event creating-client-class.s3: calling handler <function add_generate_presigned_post at 0x1070d5378>
[hooks.py       :209  ] Event creating-client-class.s3: calling handler <function lazy_call.<locals>._handler at 0x107210048>
[hooks.py       :209  ] Event creating-client-class.s3: calling handler <function add_generate_presigned_url at 0x1070d5158>
[args.py        :159  ] The s3 config key is not a dictionary type, ignoring its value of: None
[endpoint.py    :129  ] Setting s3 timeout as (60, 60)
[client.py      :179  ] Defaulting to S3 virtual host style addressing with path style addressing fallback.
[hooks.py       :209  ] Event before-parameter-build.s3.HeadObject: calling handler <function sse_md5 at 0x107110950>
[hooks.py       :209  ] Event before-parameter-build.s3.HeadObject: calling handler <function validate_bucket_name at 0x1071108c8>
[hooks.py       :209  ] Event before-parameter-build.s3.HeadObject: calling handler <bound method S3RegionRedirector.redirect_from_cache of <botocore.utils.S3RegionRedirector object at 0x109991f98>>
[hooks.py       :209  ] Event before-parameter-build.s3.HeadObject: calling handler <function generate_idempotent_uuid at 0x107110510>
[hooks.py       :209  ] Event before-call.s3.HeadObject: calling handler <function add_expect_header at 0x107110d90>
[hooks.py       :209  ] Event before-call.s3.HeadObject: calling handler <bound method S3RegionRedirector.set_request_url of <botocore.utils.S3RegionRedirector object at 0x109991f98>>
[endpoint.py    :140  ] Making request for OperationModel(name=HeadObject) (verify_ssl=True) with params: {'url_path': '/testdata.researchdata.alpha.jisc.ac.uk/unsorted/10.1002/%28SICI%291096-8628%2819960216%2967%3A1%3C40%3A%3AAID-AJMG6%3E3.0.CO%3B2-W/10-1002-%28SICI%291096-8628%2819960216%2967%3A1%3C40%3A%3AAID-AJMG6%3E3-0-CO%3B2-W.json', 'query_string': {}, 'method': 'HEAD', 'headers': {'User-Agent': 'Boto3/1.4.4 Python/3.6.1 Darwin/16.7.0 Botocore/1.5.95'}, 'body': b'', 'url': 'https://s3.eu-west-2.amazonaws.com/testdata.researchdata.alpha.jisc.ac.uk/unsorted/10.1002/%28SICI%291096-8628%2819960216%2967%3A1%3C40%3A%3AAID-AJMG6%3E3.0.CO%3B2-W/10-1002-%28SICI%291096-8628%2819960216%2967%3A1%3C40%3A%3AAID-AJMG6%3E3-0-CO%3B2-W.json', 'context': {'client_region': 'eu-west-2', 'client_config': <botocore.config.Config object at 0x1096dffd0>, 'has_streaming_input': False, 'auth_type': None, 'signing': {'bucket': 'testdata.researchdata.alpha.jisc.ac.uk'}}}
[hooks.py       :209  ] Event request-created.s3.HeadObject: calling handler <bound method RequestSigner.handler of <botocore.signers.RequestSigner object at 0x109964f98>>
[hooks.py       :209  ] Event choose-signer.s3.HeadObject: calling handler <function set_operation_specific_signer at 0x107110400>
[hooks.py       :209  ] Event before-sign.s3.HeadObject: calling handler <function fix_s3_host at 0x106fcf488>
[auth.py        :347  ] Calculating signature using v4 auth.
[auth.py        :348  ] CanonicalRequest:
HEAD
/testdata.researchdata.alpha.jisc.ac.uk/unsorted/10.1002/%28SICI%291096-8628%2819960216%2967%3A1%3C40%3A%3AAID-AJMG6%3E3.0.CO%3B2-W/10-1002-%28SICI%291096-8628%2819960216%2967%3A1%3C40%3A%3AAID-AJMG6%3E3-0-CO%3B2-W.json

host:s3.eu-west-2.amazonaws.com
x-amz-content-sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
x-amz-date:20171102T062147Z

host;x-amz-content-sha256;x-amz-date
e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
[auth.py        :350  ] StringToSign:
AWS4-HMAC-SHA256
20171102T062147Z
20171102/eu-west-2/s3/aws4_request
89209406d4d7f5f79270f1c5a0c4a3e6d28f3cf395a8aa6144d1b989073f9e37
[auth.py        :352  ] Signature:
b5920b54be5757db8da3e1f98200d5778324ea4c8d2ba558e23bf4a733540f3d
[endpoint.py    :200  ] Sending http request: <PreparedRequest [HEAD]>
[connectionpool.py:735  ] Starting new HTTPS connection (1): s3.eu-west-2.amazonaws.com
[connectionpool.py:383  ] "HEAD /testdata.researchdata.alpha.jisc.ac.uk/unsorted/10.1002/%28SICI%291096-8628%2819960216%2967%3A1%3C40%3A%3AAID-AJMG6%3E3.0.CO%3B2-W/10-1002-%28SICI%291096-8628%2819960216%2967%3A1%3C40%3A%3AAID-AJMG6%3E3-0-CO%3B2-W.json HTTP/1.1" 200 0
[parsers.py     :204  ] Response headers: {'x-amz-id-2': 'w99PZbE0YvK9OwJTAIAtbzYoS43+RIoSWHg/OTpup6wNGFjQwot+xcV8HyMH/EH/uW5lz4Kb02E=', 'x-amz-request-id': 'C45BE5577DF0EE81', 'date': 'Thu, 02 Nov 2017 06:21:31 GMT', 'last-modified': 'Tue, 24 Jan 2017 16:29:08 GMT', 'etag': '"b9ccacf2e6ee7905b378ad2c19017ee9"', 'accept-ranges': 'bytes', 'content-type': 'application/json', 'content-length': '8325', 'server': 'AmazonS3'}
[parsers.py     :205  ] Response body:
b''
[hooks.py       :209  ] Event needs-retry.s3.HeadObject: calling handler <botocore.retryhandler.RetryHandler object at 0x1074c36a0>
[retryhandler.py:187  ] No retry needed.
[hooks.py       :209  ] Event needs-retry.s3.HeadObject: calling handler <bound method S3RegionRedirector.redirect_from_error of <botocore.utils.S3RegionRedirector object at 0x109991f98>>
[controller.py  :134  ] Shutting down database session with exception.
[_internal.py   :87   ] 127.0.0.1 - - [02/Nov/2017 06:21:48] "GET /download/source/1/unsorted/10.1002/%28SICI%291096-8628%2819960216%2967:1%3C40::AID-AJMG6%3E3.0.CO%3B2-W/10-1002-%28SICI%291096-8628%2819960216%2967:1%3C40::AID-AJMG6%3E3-0-CO%3B2-W.json/ HTTP/1.1" 500 -

**Comment by carlwilson** [comment]
Fixed by #37
