### ISSUE TITLE
Reports - Report Listing - Clicking on any folder gives internal server error

### ISSUE THREAD

**Issue by zak-ahmed** [carlwilson/fmt-sniff#32]
Steps:
1. from home page click on Reports tab
2. Click on any folder under the Report Listing
Result: Gives internal error instead of reports

Logs:
[controller.py  :134  ] Shutting down database session with exception.
[_internal.py   :87   ] 127.0.0.1 - - [02/Nov/2017 06:26:23] "GET /reports/14/ HTTP/1.1" 500 -

**Comment by carlwilson** [comment]
Hi @zak-ahmed again I believe this is now fixed, please test the latest integration version and let me know.

**Comment by carlwilson** [comment]
Checked and fixed.
