### ISSUE TITLE
Download button on file details page should download an individual file report.

### ISSUE THREAD

**Issue by carlwilson** [carlwilson/fmt-sniff#44]
Currently the download button request the binary stream for the item. What's required is the ability to obtain the analysis result of the file, i.e. this information:
![image](https://user-images.githubusercontent.com/440634/32497556-d19d810c-c3c4-11e7-99cd-9ff049f98804.png)
The user will be able to specify the report format as one of:
- JSON
- PDF

**Comment by zak-ahmed** [comment]
Tested on the branch 'feat/json-reporting', download button is now available to download the report in Pdf and JSON format.
