### ISSUE TITLE
Cannot access 'Jisc Test Bucket' on the latest code

### ISSUE THREAD

**Issue by zak-ahmed** [carlwilson/fmt-sniff#58]
Tested this on "https://github.com/carlwilson/fmt-sniff/pull/57". 
Installed the latest code from the above pull request and clicked on the 'Jisc Test Bucket' link to access the s3 test data bucket. 
Getting '404 Not Found:Folder not found' message on the page. 
This was working earlier. 

Logs : 
GET
/testdata.researchdata.alpha.jisc.ac.uk
delimiter=%2F&list-type=2&prefix=%2F
host:s3.eu-west-2.amazonaws.com
x-amz-content-sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
x-amz-date:20171130T064813Z

host;x-amz-content-sha256;x-amz-date
e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
[auth.py        :350  ] StringToSign:
AWS4-HMAC-SHA256
20171130T064813Z
20171130/eu-west-2/s3/aws4_request
85bcd0fae126566b2bbe5411aa962522f330e62edd20e412e23e8fec5d91c77c
[auth.py        :352  ] Signature:
411fc29381022748ef4cc92d069e7db7be744a62eb3893e0c24b7b6378a6f1f5
[endpoint.py    :200  ] Sending http request: <PreparedRequest [GET]>
[connectionpool.py:735  ] Starting new HTTPS connection (1): s3.eu-west-2.amazonaws.com
[connectionpool.py:383  ] "GET /testdata.researchdata.alpha.jisc.ac.uk?list-type=2&prefix=%2F&delimiter=%2F HTTP/1.1" 200 None
[parsers.py     :204  ] Response headers: {'x-amz-id-2': 'aNkKRsZ/0mWwebu4O/7s8E6tNvm6jEvPgcibAEal1Oyo0pczGWWHnk8XUW33aIIBbK0LB0ljfDk=', 'x-amz-request-id': '3F61F8AF3F47EFB3', 'date': 'Thu, 30 Nov 2017 06:48:14 GMT', 'x-amz-bucket-region': 'eu-west-2', 'content-type': 'application/xml', 'transfer-encoding': 'chunked', 'server': 'AmazonS3'}
[parsers.py     :205  ] Response body:
b'<?xml version="1.0" encoding="UTF-8"?>\n<ListBucketResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><Name>testdata.researchdata.alpha.jisc.ac.uk</Name><Prefix>/</Prefix><KeyCount>0</KeyCount><MaxKeys>1000</MaxKeys><Delimiter>/</Delimiter><IsTruncated>false</IsTruncated></ListBucketResult>'
[hooks.py       :209  ] Event needs-retry.s3.ListObjectsV2: calling handler <botocore.retryhandler.RetryHandler object at 0x110bc92e8>
[retryhandler.py:187  ] No retry needed.
[hooks.py       :209  ] Event needs-retry.s3.ListObjectsV2: calling handler <bound method S3RegionRedirector.redirect_from_error of <botocore.utils.S3RegionRedirector object at 0x10c4cceb8>>
[_internal.py   :87   ] 127.0.0.1 - - [30/Nov/2017 06:48:13] "GET /source/1/folder/ HTTP/1.1" 200 -
[_internal.py   :87   ] 127.0.0.1 - - [30/Nov/2017 06:48:13] "GET /favicon.ico HTTP/1.1" 200 -

**Comment by carlwilson** [comment]
This has been fixed with recent merges and was to do with root directory access problems.
