### ISSUE TITLE
'Property Value' links on the Property details page gives Internal Server errror

### ISSUE THREAD

**Issue by zak-ahmed** [carlwilson/fmt-sniff#59]
Tested on pull request 'https://github.com/carlwilson/fmt-sniff/pull/57'

1) Run 'Analyse' by clicking 'Analyse sub-folders' checkbox on any folder.
2) Report will be generated and added to the Report tab
3) Go to 'Reports' tab and click on the link under 'Source' column
4) click on the link under 'Property' column on 'report details' page
5) Click on the link under 'Property Value' column on Property details page
Expected : User should be taken to the details report of the individual file
Actual : User is taken to the internal server error page

Logs: 
[controller.py  :209  ] Got 0 Key properties
[controller.py  :213  ] Got 1 Byte properties
[controller.py  :255  ] Shutting down database session with exception.
[_internal.py   :87   ] 127.0.0.1 - - [30/Nov/2017 07:05:09] "GET /reports/1/prop/3/propval/8 HTTP/1.1" 500 -
[_internal.py   :87   ] 127.0.0.1 - - [30/Nov/2017 07:05:09] "GET /favicon.ico HTTP/1.1" 200 -

**Comment by carlwilson** [comment]
This appears to be working now, I'm going to close but @zak-ahmed feel free to re-open if you disagree.
